from PyQt5 import QtCore, QtGui, QtWidgets

grafo = { "Itumbiara": { "Centralina" : 20, "Tupaciguara" : 55},
          "Centralina": { "Itumbiara" : 20, "Capinópolis" : 40, "Monte Alegre" : 75},
          "Tupaciguara": { "Monte Alegre": 44, "Itumbiara": 55, "Uberlândia": 60},
          "Capinópolis": {"Ituiutaba": 30, "Centralina": 40},
          "Monte Alegre": {"Douradinhos": 28, "Tupaciguara": 44, "Uberlândia": 60, "Centralina": 75, "Ituiutaba": 85},
          "Uberlândia": {"Araguari": 30, "Indianópolis": 45, "Tupaciguara": 60, "Monte Alegre": 60, "Douradinhos": 63, "Romaria": 78 },
          "Ituiutaba": {"Capinópolis": 30, "Monte Alegre": 85, "Douradinhos": 90},
          "Douradinhos": {"Monte Alegre": 28, "Uberlândia": 63, "Ituiutaba": 90},
          "Araguari": {"Cascalho Rico": 28, "Uberlândia": 30, "Estrela do Sul": 34},
          "Indianópolis": {"São Juliana": 40, "Uberlândia": 45},
          "Romaria": {"Estrela do Sul": 27, "São Juliana": 28, "Uberlândia": 78},
          "Cascalho Rico": {"Araguari": 28, "Grupiara": 32},
          "Estrela do Sul": {"Romaria": 27, "Araguari": 34, "Grupiara": 38},
          "São Juliana": {"Romaria": 28, "Indianópolis": 40},
          "Grupiara": {"Cascalho Rico": 32, "Estrela do Sul":38}        
}
    
def dijkstra_path(grafo, origem, fim, command): #retorna a menor distancia de um No origem até um No destino e o caminho até ele

    controle = { }
    distanciaAtual = { }
    noAtual = { }
    naoVisitados = []
    atual = origem
    noAtual[atual] = 0

    
    for vertice in grafo.keys():
        naoVisitados.append(vertice) #inclui os vertices nos não visitados    
        distanciaAtual[vertice] = float('inf') #inicia os vertices como infinito

    distanciaAtual[atual] = [0,origem] 

    naoVisitados.remove(atual)

    while naoVisitados:
        for vizinho, peso in grafo[atual].items():
             pesoCalc = peso + noAtual[atual]
             if distanciaAtual[vizinho] == float("inf") or distanciaAtual[vizinho][0] > pesoCalc:
                 distanciaAtual[vizinho] = [pesoCalc,atual]
                 controle[vizinho] = pesoCalc
                 
        if controle == {} : break    
        minVizinho = min(controle.items(), key=lambda x: x[1]) #seleciona o menor vizinho
        atual=minVizinho[0]
        noAtual[atual] = minVizinho[1]
        naoVisitados.remove(atual)
        del controle[atual]
    path = []
    if command == "path":
        return (printPath(distanciaAtual,origem, fim, path))
    elif command == "distance":
        return ("A menor distância de %s atá %s é: %s Km" % (origem, fim, distanciaAtual[fim][0]))
 

def printPath(distancias,inicio, fim, path):
        if  fim != inicio:
            path.append(fim)
            return printPath(distancias,inicio, distancias[fim][1], path)
        else:
            path.append(fim)
            return path



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 688)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Ituiutaba = QtWidgets.QPushButton(self.centralwidget)
        self.Ituiutaba.setGeometry(QtCore.QRect(90, 310, 81, 41))
        self.Ituiutaba.setObjectName("Ituiutaba")
        self.Capinpolis = QtWidgets.QPushButton(self.centralwidget)
        self.Capinpolis.setGeometry(QtCore.QRect(20, 170, 81, 41))
        self.Capinpolis.setObjectName("Capinópolis")
        self.Centralina = QtWidgets.QPushButton(self.centralwidget)
        self.Centralina.setGeometry(QtCore.QRect(220, 130, 81, 41))
        self.Centralina.setObjectName("Centralina")
        self.Itumbiara = QtWidgets.QPushButton(self.centralwidget)
        self.Itumbiara.setGeometry(QtCore.QRect(210, 40, 81, 41))
        self.Itumbiara.setObjectName("Itumbiara")
        self.MonteAlegre = QtWidgets.QPushButton(self.centralwidget)
        self.MonteAlegre.setGeometry(QtCore.QRect(390, 240, 91, 41))
        self.MonteAlegre.setObjectName("Monte Alegre")
        self.Tupaciguara = QtWidgets.QPushButton(self.centralwidget)
        self.Tupaciguara.setGeometry(QtCore.QRect(450, 110, 81, 41))
        self.Tupaciguara.setObjectName("Tupaciguara")
        self.Douradinhos = QtWidgets.QPushButton(self.centralwidget)
        self.Douradinhos.setGeometry(QtCore.QRect(430, 350, 81, 41))
        self.Douradinhos.setObjectName("Douradinhos")
        self.Uberlandia = QtWidgets.QPushButton(self.centralwidget)
        self.Uberlandia.setGeometry(QtCore.QRect(650, 260, 81, 41))
        self.Uberlandia.setObjectName("Uberlândia")
        self.Araguari = QtWidgets.QPushButton(self.centralwidget)
        self.Araguari.setGeometry(QtCore.QRect(770, 170, 81, 41))
        self.Araguari.setObjectName("Araguari")
        self.CascalhoRico = QtWidgets.QPushButton(self.centralwidget)
        self.CascalhoRico.setGeometry(QtCore.QRect(900, 100, 81, 41))
        self.CascalhoRico.setObjectName("Cascalho Rico")
        self.Grupiara = QtWidgets.QPushButton(self.centralwidget)
        self.Grupiara.setGeometry(QtCore.QRect(1000, 30, 81, 41))
        self.Grupiara.setObjectName("Grupiara")
        self.EstreladoSul = QtWidgets.QPushButton(self.centralwidget)
        self.EstreladoSul.setGeometry(QtCore.QRect(1000, 200, 91, 41))
        self.EstreladoSul.setObjectName("Estrela do Sul")
        self.Romaria = QtWidgets.QPushButton(self.centralwidget)
        self.Romaria.setGeometry(QtCore.QRect(1040, 290, 81, 41))
        self.Romaria.setObjectName("Romaria")
        self.Indianopolis = QtWidgets.QPushButton(self.centralwidget)
        self.Indianopolis.setGeometry(QtCore.QRect(800, 370, 81, 41))
        self.Indianopolis.setObjectName("Indianópolis")
        self.SaoJuliana = QtWidgets.QPushButton(self.centralwidget)
        self.SaoJuliana.setGeometry(QtCore.QRect(1030, 410, 81, 41))
        self.SaoJuliana.setObjectName("São Juliana")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(120, 200, 21, 111))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(100, 190, 31, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(180, 150, 20, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(320, 270, 20, 51))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(100, 170, 91, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(190, 140, 31, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(170, 310, 161, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.centralwidget)
        self.line_9.setGeometry(QtCore.QRect(170, 330, 211, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(330, 260, 61, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_10 = QtWidgets.QFrame(self.centralwidget)
        self.line_10.setGeometry(QtCore.QRect(380, 360, 51, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(370, 340, 20, 31))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(450, 280, 20, 71))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.centralwidget)
        self.line_13.setGeometry(QtCore.QRect(230, 80, 51, 51))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.centralwidget)
        self.line_14.setGeometry(QtCore.QRect(290, 50, 201, 21))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.centralwidget)
        self.line_15.setGeometry(QtCore.QRect(510, 360, 161, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.centralwidget)
        self.line_16.setGeometry(QtCore.QRect(480, 60, 20, 51))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(self.centralwidget)
        self.line_17.setGeometry(QtCore.QRect(300, 140, 91, 16))
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(self.centralwidget)
        self.line_18.setGeometry(QtCore.QRect(410, 210, 20, 31))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(self.centralwidget)
        self.line_19.setGeometry(QtCore.QRect(380, 150, 21, 61))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(self.centralwidget)
        self.line_20.setGeometry(QtCore.QRect(390, 200, 31, 16))
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.line_21 = QtWidgets.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(450, 180, 3, 61))
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(self.centralwidget)
        self.line_22.setGeometry(QtCore.QRect(450, 170, 41, 16))
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_23 = QtWidgets.QFrame(self.centralwidget)
        self.line_23.setGeometry(QtCore.QRect(480, 150, 20, 31))
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.line_24 = QtWidgets.QFrame(self.centralwidget)
        self.line_24.setGeometry(QtCore.QRect(480, 260, 118, 3))
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.line_25 = QtWidgets.QFrame(self.centralwidget)
        self.line_25.setGeometry(QtCore.QRect(590, 260, 20, 21))
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.line_26 = QtWidgets.QFrame(self.centralwidget)
        self.line_26.setGeometry(QtCore.QRect(600, 270, 51, 16))
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.line_27 = QtWidgets.QFrame(self.centralwidget)
        self.line_27.setGeometry(QtCore.QRect(530, 120, 141, 20))
        self.line_27.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.line_28 = QtWidgets.QFrame(self.centralwidget)
        self.line_28.setGeometry(QtCore.QRect(660, 130, 20, 131))
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.line_29 = QtWidgets.QFrame(self.centralwidget)
        self.line_29.setGeometry(QtCore.QRect(700, 190, 20, 71))
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.line_30 = QtWidgets.QFrame(self.centralwidget)
        self.line_30.setGeometry(QtCore.QRect(710, 180, 61, 16))
        self.line_30.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.line_31 = QtWidgets.QFrame(self.centralwidget)
        self.line_31.setGeometry(QtCore.QRect(660, 300, 20, 71))
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.line_32 = QtWidgets.QFrame(self.centralwidget)
        self.line_32.setGeometry(QtCore.QRect(700, 300, 16, 91))
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.line_33 = QtWidgets.QFrame(self.centralwidget)
        self.line_33.setGeometry(QtCore.QRect(710, 380, 91, 20))
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.line_34 = QtWidgets.QFrame(self.centralwidget)
        self.line_34.setGeometry(QtCore.QRect(730, 270, 221, 16))
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.line_35 = QtWidgets.QFrame(self.centralwidget)
        self.line_35.setGeometry(QtCore.QRect(947, 300, 91, 20))
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.line_36 = QtWidgets.QFrame(self.centralwidget)
        self.line_36.setGeometry(QtCore.QRect(940, 280, 20, 31))
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.line_37 = QtWidgets.QFrame(self.centralwidget)
        self.line_37.setGeometry(QtCore.QRect(810, 110, 91, 20))
        self.line_37.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.line_38 = QtWidgets.QFrame(self.centralwidget)
        self.line_38.setGeometry(QtCore.QRect(800, 120, 20, 51))
        self.line_38.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.line_39 = QtWidgets.QFrame(self.centralwidget)
        self.line_39.setGeometry(QtCore.QRect(850, 180, 81, 16))
        self.line_39.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_39.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_39.setObjectName("line_39")
        self.line_40 = QtWidgets.QFrame(self.centralwidget)
        self.line_40.setGeometry(QtCore.QRect(920, 190, 20, 31))
        self.line_40.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_40.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_40.setObjectName("line_40")
        self.line_41 = QtWidgets.QFrame(self.centralwidget)
        self.line_41.setGeometry(QtCore.QRect(930, 210, 71, 20))
        self.line_41.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_41.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_41.setObjectName("line_41")
        self.line_42 = QtWidgets.QFrame(self.centralwidget)
        self.line_42.setGeometry(QtCore.QRect(1040, 70, 20, 131))
        self.line_42.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_42.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_42.setObjectName("line_42")
        self.line_43 = QtWidgets.QFrame(self.centralwidget)
        self.line_43.setGeometry(QtCore.QRect(1020, 70, 20, 51))
        self.line_43.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_43.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_43.setObjectName("line_43")
        self.line_44 = QtWidgets.QFrame(self.centralwidget)
        self.line_44.setGeometry(QtCore.QRect(977, 110, 51, 20))
        self.line_44.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_44.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_44.setObjectName("line_44")
        self.line_45 = QtWidgets.QFrame(self.centralwidget)
        self.line_45.setGeometry(QtCore.QRect(1060, 240, 20, 51))
        self.line_45.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_45.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_45.setObjectName("line_45")
        self.line_46 = QtWidgets.QFrame(self.centralwidget)
        self.line_46.setGeometry(QtCore.QRect(1070, 330, 20, 81))
        self.line_46.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_46.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_46.setObjectName("line_46")
        self.line_47 = QtWidgets.QFrame(self.centralwidget)
        self.line_47.setGeometry(QtCore.QRect(880, 380, 91, 16))
        self.line_47.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_47.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_47.setObjectName("line_47")
        self.line_48 = QtWidgets.QFrame(self.centralwidget)
        self.line_48.setGeometry(QtCore.QRect(967, 420, 61, 20))
        self.line_48.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_48.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_48.setObjectName("line_48")
        self.line_49 = QtWidgets.QFrame(self.centralwidget)
        self.line_49.setGeometry(QtCore.QRect(960, 390, 20, 41))
        self.line_49.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_49.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_49.setObjectName("line_49")
        self.line_50 = QtWidgets.QFrame(self.centralwidget)
        self.line_50.setGeometry(QtCore.QRect(0, 480, 1141, 16))
        self.line_50.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_50.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_50.setObjectName("line_50")
        self.entrada_1 = QtWidgets.QComboBox(self.centralwidget)
        self.entrada_1.setGeometry(QtCore.QRect(940, 520, 161, 22))
        self.entrada_1.setDuplicatesEnabled(True)
        self.entrada_1.setObjectName("entrada_1")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.entrada_1.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(940, 495, 161, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(940, 545, 161, 21))
        self.label_2.setObjectName("label_2")
        self.Enter = QtWidgets.QPushButton(self.centralwidget)
        self.Enter.setGeometry(QtCore.QRect(980, 600, 93, 28))
        self.Enter.setObjectName("Enter")
        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        self.Reset.setGeometry(QtCore.QRect(980, 630, 93, 28))
        self.Reset.setObjectName("Reset")
        self.resultado = QtWidgets.QLabel(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(100, 540, 601, 61))
        self.resultado.setText("")
        self.resultado.setTextFormat(QtCore.Qt.RichText)
        self.resultado.setObjectName("resultado")
        self.entrada_2 = QtWidgets.QComboBox(self.centralwidget)
        self.entrada_2.setGeometry(QtCore.QRect(940, 570, 161, 22))
        self.entrada_2.setDuplicatesEnabled(True)
        self.entrada_2.setObjectName("entrada_2")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        self.entrada_2.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Ituiutaba.setText(_translate("MainWindow", "Ituiutaba"))
        self.Capinpolis.setText(_translate("MainWindow", "Capinópolis"))
        self.Centralina.setText(_translate("MainWindow", "Centralina"))
        self.Itumbiara.setText(_translate("MainWindow", "Itumbiara"))
        self.MonteAlegre.setText(_translate("MainWindow", "Monte Alegre"))
        self.Tupaciguara.setText(_translate("MainWindow", "Tupaciguara"))
        self.Douradinhos.setText(_translate("MainWindow", "Douradinho"))
        self.Uberlandia.setText(_translate("MainWindow", "Uberlândia"))
        self.Araguari.setText(_translate("MainWindow", "Araguari"))
        self.CascalhoRico.setText(_translate("MainWindow", "Cascalho \n""Rico"))
        self.Grupiara.setText(_translate("MainWindow", "Grupiara"))
        self.EstreladoSul.setText(_translate("MainWindow", "Estrela do Sul"))
        self.Romaria.setText(_translate("MainWindow", "Romaria"))
        self.Indianopolis.setText(_translate("MainWindow", "Indianópolis"))
        self.SaoJuliana.setText(_translate("MainWindow", "São Juliana"))
        self.entrada_1.setItemText(0, _translate("MainWindow", "Escolha uma Cidade"))
        self.entrada_1.setItemText(1, _translate("MainWindow", "Itumbiara"))
        self.entrada_1.setItemText(2, _translate("MainWindow", "Capinópolis"))
        self.entrada_1.setItemText(3, _translate("MainWindow", "Ituiutaba"))
        self.entrada_1.setItemText(4, _translate("MainWindow", "Centralina"))
        self.entrada_1.setItemText(5, _translate("MainWindow", "Monte Alegre"))
        self.entrada_1.setItemText(6, _translate("MainWindow", "Tupaciguara"))
        self.entrada_1.setItemText(7, _translate("MainWindow", "Douradinho"))
        self.entrada_1.setItemText(8, _translate("MainWindow", "Uberlândia"))
        self.entrada_1.setItemText(9, _translate("MainWindow", "Araguari"))
        self.entrada_1.setItemText(10, _translate("MainWindow", "Cascalho Rico"))
        self.entrada_1.setItemText(11, _translate("MainWindow", "Grupiara"))
        self.entrada_1.setItemText(12, _translate("MainWindow", "Estrela do Sul"))
        self.entrada_1.setItemText(13, _translate("MainWindow", "Romaria"))
        self.entrada_1.setItemText(14, _translate("MainWindow", "São Juliana"))
        self.entrada_1.setItemText(15, _translate("MainWindow", "Indianópolis"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Origem:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Destino:</span></p></body></html>"))
        self.Enter.setText(_translate("MainWindow", "Enter"))
        self.Reset.setText(_translate("MainWindow", "Reset"))
        self.entrada_2.setItemText(0, _translate("MainWindow", "Escolha uma Cidade"))
        self.entrada_2.setItemText(1, _translate("MainWindow", "Itumbiara"))
        self.entrada_2.setItemText(2, _translate("MainWindow", "Capinópolis"))
        self.entrada_2.setItemText(3, _translate("MainWindow", "Ituiutaba"))
        self.entrada_2.setItemText(4, _translate("MainWindow", "Centralina"))
        self.entrada_2.setItemText(5, _translate("MainWindow", "Monte Alegre"))
        self.entrada_2.setItemText(6, _translate("MainWindow", "Tupaciguara"))
        self.entrada_2.setItemText(7, _translate("MainWindow", "Douradinhos"))
        self.entrada_2.setItemText(8, _translate("MainWindow", "Uberlândia"))
        self.entrada_2.setItemText(9, _translate("MainWindow", "Araguari"))
        self.entrada_2.setItemText(10, _translate("MainWindow", "Cascalho Rico"))
        self.entrada_2.setItemText(11, _translate("MainWindow", "Grupiara"))
        self.entrada_2.setItemText(12, _translate("MainWindow", "Estrela do Sul"))
        self.entrada_2.setItemText(13, _translate("MainWindow", "Romaria"))
        self.entrada_2.setItemText(14, _translate("MainWindow", "São Juliana"))
        self.entrada_2.setItemText(15, _translate("MainWindow", "Indianópolis"))
        self.Enter.clicked.connect(self.funcao)
        self.Reset.clicked.connect(self.reset)

    def funcao(self):
        self.resultado.setText(dijkstra_path(grafo, self.entrada_1.currentText(), self.entrada_2.currentText(), "distance"))
        cidades = dijkstra_path(grafo, self.entrada_1.currentText(), self.entrada_2.currentText(), "path") 
        for i in range(len(cidades)):
            if(self.Uberlandia.objectName()==cidades[i]):
                self.Uberlandia.setStyleSheet("background-color:#8fd34b;") 
            elif(self.Ituiutaba.objectName()==cidades[i]):
                self.Ituiutaba.setStyleSheet("background-color:#8fd34b;")
            elif(self.Capinpolis.objectName()==cidades[i]):
                self.Capinpolis.setStyleSheet("background-color:#8fd34b;")
            elif(self.Centralina.objectName()==cidades[i]):
                self.Centralina.setStyleSheet("background-color:#8fd34b;")
            elif(self.Itumbiara.objectName()==cidades[i]):
                self.Itumbiara.setStyleSheet("background-color:#8fd34b;")
            elif(self.MonteAlegre.objectName()==cidades[i]):
                self.MonteAlegre.setStyleSheet("background-color:#8fd34b;")
            elif(self.Tupaciguara.objectName()==cidades[i]):
                self.Tupaciguara.setStyleSheet("background-color:#8fd34b;")
            elif(self.Douradinhos.objectName()==cidades[i]):
                self.Douradinhos.setStyleSheet("background-color:#8fd34b;")
            elif(self.Araguari.objectName()==cidades[i]):
                self.Araguari.setStyleSheet("background-color:#8fd34b;")
            elif(self.CascalhoRico.objectName()==cidades[i]):
                self.CascalhoRico.setStyleSheet("background-color:#8fd34b;")
            elif(self.Grupiara.objectName()==cidades[i]):
                self.Grupiara.setStyleSheet("background-color:#8fd34b;")
            elif(self.EstreladoSul.objectName()==cidades[i]):
                self.EstreladoSul.setStyleSheet("background-color:#8fd34b;")
            elif(self.Romaria.objectName()==cidades[i]):
                self.Romaria.setStyleSheet("background-color:#8fd34b;")
            elif(self.SaoJuliana.objectName()==cidades[i]):
                self.SaoJuliana.setStyleSheet("background-color:#8fd34b;")
            elif(self.Indianopolis.objectName()==cidades[i]):
                self.Indianopolis.setStyleSheet("background-color:#8fd34b;")
    
    def reset(self):
        self.resultado.setText("")
        self.Uberlandia.setStyleSheet("background-color:#e1e1e0;")
        self.Araguari.setStyleSheet("background-color:#e1e1e0;")
        self.Indianopolis.setStyleSheet("background-color:#e1e1e0;")
        self.MonteAlegre.setStyleSheet("background-color:#e1e1e0;")
        self.SaoJuliana.setStyleSheet("background-color:#e1e1e0;")
        self.Itumbiara.setStyleSheet("background-color:#e1e1e0;")
        self.Ituiutaba.setStyleSheet("background-color:#e1e1e0;")
        self.Tupaciguara.setStyleSheet("background-color:#e1e1e0;")
        self.CascalhoRico.setStyleSheet("background-color:#e1e1e0;")
        self.Centralina.setStyleSheet("background-color:#e1e1e0;")
        self.Grupiara.setStyleSheet("background-color:#e1e1e0;")
        self.Capinpolis.setStyleSheet("background-color:#e1e1e0;")
        self.Douradinhos.setStyleSheet("background-color:#e1e1e0;")
        self.Romaria.setStyleSheet("background-color:#e1e1e0;")
        self.EstreladoSul.setStyleSheet("background-color:#e1e1e0;")
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
